//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AfterWorkPlanner.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class ActivityUserMapping
    {
        public int Id { get; set; }

        [DisplayName("User Name")]
        public int user_id { get; set; }

        [DisplayName("Activity Name")]
        public int activity_id { get; set; }

        [DisplayName("Time Limit")]
        public decimal time_limit { get; set; }

        [DisplayName("From Time")]
        public System.DateTime from_time { get; set; }

        [DisplayName("To Time")]
        public System.DateTime to_time { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual User User { get; set; }
    }
}
