//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AfterWorkPlanner.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Role
    {
        public int role_id { get; set; }

        [DisplayName("Role Name")]
        public string role_name { get; set; }

        [DisplayName("User Name")]
        public int user_id { get; set; }

        public bool Edit { get; set; }

        public bool Create { get; set; }

        public bool Delete { get; set; }

        public bool View { get; set; }

        [DisplayName("Created Date Time")]
        public System.DateTime created_dt_tm { get; set; }

        [DisplayName("Modified Date Time")]
        public System.DateTime modified_dt_tm { get; set; }
    
        public virtual User User { get; set; }
    }
}
