//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AfterWorkPlanner.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Roles = new HashSet<Role>();
            this.ActivityUserMappings = new HashSet<ActivityUserMapping>();
        }
    
        public int user_id { get; set; }

        [DisplayName("User Name")]
        public string user_name { get; set; }

        [DisplayName("User Password")]
        public string user_pwd { get; set; }

        [DisplayName("Created Date Time")]
        public System.DateTime created_dt_tm { get; set; }

        [DisplayName("Modified Date Time")]
        public System.DateTime modified_dt_tm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role> Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityUserMapping> ActivityUserMappings { get; set; }
    }
}
